version: '3.8'
services:
  app:
    container_name: golang
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mydb_p@ssw0rd
      - MYSQL_DB=typing_tournament
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    tty: true
    build: .
    ports:
      - 1324:1324
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - learning

  mysql:
    image: mysql:latest
    container_name: mysql_golang
    environment:
      - MYSQL_USER=default
      - MYSQL_PASSWORD=mydb_p@ssw0rd
      - MYSQL_DB=typing_tournament
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - learning

volumes:
  mysql_data:
    name: golang_mysql
    driver: local

networks:
  learning:
    driver: bridge